config/routes.rb
InterviewApp::Application.routes.draw do

  get "recipes/create"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :recipes, :only => [:create, :destroy]

  match '/contact', :to => 'pages#contact', :as => :contact
  match '/about', :to => 'pages#about', :as => :about
  match '/help', :to => 'pages#help', :as => :help
  match '/home', :to => 'pages#home', :as => :home
  match '/login', :to => 'sessions#new', :as => :login
  match '/logout', :to => 'sessions#destroy', :as => :logout
  match '/signup', :to => 'users#new', :as => :signup
  root :to => "pages#home"

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :instructions, :title, :num_served, :ingredients
  
  belongs_to :user
  
  validates :num_served, :presence => true
  validates :title, :presence => true,
                    :length => { :maximum => 15, :minimum => 4}
  validates :ingredients, :presence => true
  validates :instructions, :presence => true,
                           :length => { :maximum => 512 }
  validates :user_id, :presence => true
  
  default_scope :order => 'recipes.created_at DESC'
  
  
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :recipes, :dependent => :destroy
  
  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :uniqueness => true
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }
                       
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password) 
    user = find_by_email(email) 
    return nil if user.nil? 
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt) 
    user = find_by_id(id) 
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  def recipebox
    Recipe.where("user_id = ?", id)
  end
  
  private
  def encrypt_password
    self.salt = make_salt if new_record? #Remove this to introduce a bug where modifying user changes their password - good idea?
    self.encrypted_password = encrypt(password)
  end
  
  def encrypt(string) 
    secure_hash("#{salt}--#{string}")
  end
  
  def make_salt 
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string) 
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    if signed_in?
      @recipe = Recipe.new
      @recipebox_items = current_user.recipebox.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy
  
  def create
    @recipe = current_user.recipes.build(params[:recipe])
    if @recipe.save
      flash[:success] = "Now we're cooking!"
      redirect_to root_path
    else
      @recipebox_items = []
      render 'pages/home'
    end
  end
  
  def destroy
    @recipe.destroy
    redirect_back_or_root_path
  end

  private
    def authorized_user
      @recipe = Recipe.find(params[:id])
      redirect_to root_path unless current_user?(@recipe.user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Log in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil? 
      #TODO Replace this with just plain flash[:error] so it lasts too long
      flash.now[:error] = "Invalid email/password combination." 
      @title = "Sign in" 
      render 'new'
    else 
      sign_in user 
      redirect_to user
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :index, :update]
  before_filter :admin_user,	:only => :destroy
  
  def new
    @user = User.new
    @title = "Sign Up"
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
    @recipes = @user.recipes.paginate(:page => params[:page])
  end
  
  def index
    @title = "Meet everybody"
    @users = User.paginate(:page => params[:page])
  end
  
  def create
    @user = User.new(params[:user]) 
    if @user.save
      sign_in @user
      flash[:success] = "Congratulations, and thanks for signing up!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new' 
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @title = "Edit yourself" 
  end
  
  def update
    @user = User.find(params[:id]) 
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user 
    else
      @title = "Edit user"
      render 'edit' 
    end
  end
  
  def destroy
    User.find(params[:id]).destroy 
    flash[:success] = "User destroyed." 
    redirect_to users_path
  end
  
  private
    
    def admin_user
      redirect_to(root_path) unless (current_user && current_user.admin?)
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis. 
  def title
    base_title = "Interview App - " 
    if @title.nil?
      base_title 
    else
      "#{base_title} | #{@title}" 
    end
  end
  
  def logo
    image_tag("logo.png", :alt => "Interview App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user) 
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def deny_access
    redirect_to login_path, :notice => "Please sign in to access this page." 
  end
  
  private
    def user_from_remember_token 
      User.authenticate_with_salt(*remember_token)
    end
  
    def remember_token 
      cookies.signed[:remember_token] || [nil, nil]
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar', 
                                            :gravatar => options)
  end

end

app/views/layouts/_footer.html.erb
<footer> 
  <nav class="round">
    <ul> 
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Contact", contact_path %></li> 
      <li><%= link_to "Abakas", "http://www.abakas.com", :popup => true %></li>
    </ul> 
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul> 
      <li><%= link_to "Share", home_path %></li>
      <li><%= link_to "Help", help_path %></li> 
      <% if signed_in? %>
        <li><%= link_to "Me", current_user %></li>
        <li><%= link_to "Meet", users_path %></li>
        <li><%= link_to "Profile", edit_user_path(current_user) %></li>
        <li><%= link_to "Log out", logout_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </u1>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]> 
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> 
<![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
  <div id="content">
    <div class="container"> 
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
    <%= render 'layouts/footer' %>
  </div>
  <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/pages/about.html.erb
<h1>
  About InterviewApp
</h1>
<p>
  InterviewApp is intended to help testers show off their skills in an interview situation.
</p>

app/views/pages/contact.html.erb
<h1>
  Contact Abakas
</h1>
<p>
  For assistance, go to <a href="http://www.abakas.com">www.abakas.com</a>
</p>

app/views/pages/help.html.erb
<h1>Help</h1> 
<p>
This application is designed to created and share recipes, and to look at recipes other people have entered. If you need help filling out a form, then I'm sort of scared of your basic living skills and I kind of don't want to see you cook. Thanks, though!
</p>

app/views/pages/home.html.erb
<% if signed_in? %> 
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main"> 
        <h1 class="recipe">What's cooking?</h1> 
        <%= render 'shared/recipe_form' %>
        <%= render 'shared/recipebox' %>
      </td> 
      <td class="sidebar round">
        <%= render 'shared/user_info' %> 
      </td>
    </tr>
  </table>
<% else %>
  <h1>
    Join Us!
  </h1>
  <p>
    Are you a recipe monster? A chef in the making? A sucker for a teaspoon? Come on in and join us!
  </p>
  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>

app/views/recipes/_recipe.html.erb
<tr> 
  <td class="recipe">
    <span class="title"><%= recipe.title %> </span>
    <span class="servings">(Serves <%=recipe.num_served%>)</span><br/>
    <span class="fieldname">Ingredients:</span>
    <span class="instructions"><%= recipe.ingredients %></span><br/>
    <span class="fieldname">Instructions:</span>
    <span class="instructions"><%= recipe.instructions %></span><br/>
    <span class="timestamp">
      Posted <%= time_ago_in_words(recipe.created_at) %> ago. 
    </span>
  </td>
</tr>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %> 
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %> prohibited this user from being saved:
    </h2>
    <p>There were problems with the following fields:</p> 
    <ul> 
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> 
      <% end %> 
    </ul>
  </div> 
<% end %>

app/views/shared/_recipe_form.html.erb
<%= form_for @recipe do |f| %> 
  <%= render 'shared/error_messages', :object => f.object %> 
  <div class="field">
    Title:
    <%= f.text_field :title %> 
  </div>
  <div class="field">
    Servings: 
    <%= f.text_field :num_served %> 
  </div>
  <div class="field">
    Ingredients: 
    <%= f.text_area :ingredients %> 
  </div>
  <div class="field">
    Instructions:
    <%= f.text_area :instructions %> 
  </div>
  <div class="actions"> 
    <%= f.submit "Cook!" %>
  </div> 
<% end %>

app/views/shared/_recipebox.html.erb
<% unless @recipebox_items.empty? %> 
  <table class="recipes" summary="User recipes">
    <%= render :partial => 'shared/recipebox_item', 
                :collection => @recipebox_items %>
  </table>
  <%= will_paginate @recipebox_items %> 
<% end %>

app/views/shared/_recipebox_item.html.erb
<tr> 
  <td class="gravatar">
    <%= link_to gravatar_for(recipebox_item.user), recipebox_item.user %> 
  </td>
  <td class="recipe"> 
    <span class="user">
      <%= link_to recipebox_item.title, recipebox_item.user %> 
    </span>
    <span class="instructions">
      Serves <%= recipebox_item.num_served %>
    </span> 
    <span class="timestamp">
      Posted <%= time_ago_in_words(recipebox_item.created_at) %> ago. 
    </span>
  </td>
</tr>

app/views/shared/_user_info.html.erb
<div class="user_info"> 
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %> 
    <span class="user_name">
      <%= current_user.name %> 
    </span>
    <span class="recipes"> 
      <%= pluralize(current_user.recipes.count, "recipe") %>
    </span> 
  </a>
</div>

app/views/users/_user.html.erb
<li> 
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %> 
  <% if current_user.admin? %> 
    | <%= link_to "delete", user, :method => :delete, 
                                  :confirm => "Really?",
                                  :title => "Delete #{user.name}" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<p>Change your mind, change yourself - just let us know!</p>

<%= form_for(@user) do |f| %> 
  <%= render 'shared/error_messages', :object => f.object %> 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %> 
  </div>
  <div class="field"> 
    <%= f.label :email %><br /> 
    <%= f.text_field :email %>
  </div> 
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %> 
  </div>
  <div class="field"> 
    <%= f.label :password_confirmation, "Confirmation" %><br /> 
    <%= f.password_field :password_confirmation %>
  </div> 
  <div class="actions">
    <%= f.submit "Update" %> 
  </div>
<% end %>
<div> 
  <%= gravatar_for @user %> 
  <a href="http://gravatar.com/emails">modify</a>
</div>

app/views/users/index.html.erb
<h1>Everybody</h1>

<p>Meet the gang</p>

<%= will_paginate %>

<ul class="users"> 
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Sign up for our best recipe database</p>
<%= form_for(@user) do |f| %> 
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %> </div>
  <div class="field">
    <%= f.label :email %><br /> 
    <%= f.text_field :email %>
  </div> 
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %> 
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %> 
  </div>
  <div class="actions"> 
    <%= f.submit "Sign up" %>
  </div> 
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information"> 
  <tr>
    <td class="main"> 
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %> 
      </h1>
      <% unless @user.recipes.empty? %> 
        <table class="recipes" summary="User recipes">
        <%= render @recipes %> </table>
        <%= will_paginate @recipes %> 
      <% end %>
    </td> 
    <td class="sidebar round">
      <strong>Name</strong> <%= link_to @user.name, @user %><br/>
      <strong>Recipes</strong> <%= @user.recipes.count %>
    </td>
  </tr> 
</table>